const RESPONSE_SUCCESS = 'RESPONSE_SUCCESS';
const RESPONSE_FAIL = 'RESPONSE_FAIL';
const USER_STATUS = 'USER_STATUS';
const GET_SINGLE_BOOK = 'GET_SINGLE_BOOK';
const UPDATE_BOOK = 'UPDATE_BOOK';

export { RESPONSE_FAIL, RESPONSE_SUCCESS, USER_STATUS, GET_SINGLE_BOOK, UPDATE_BOOK };
